name: Compile Kernel for AOSP
# this gh workflows is from vbajs
# credits to vbajs

on:
  workflow_dispatch:

jobs:
  build:
    name: Compiling by ${{ github.actor }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install bc build-essential bison flex zip p7zip-full libc6 curl libstdc++6 git wget libssl-dev zstd lld python3 -y

      - name: Set Build Variables
        run: |
          echo "ZIPNAME=Maiar-v1.0-Silmaril-$(date '+%Y%m%d-%H%M').zip" >> $GITHUB_ENV

      - name: Set Git identity for ${{ github.actor }}
        run: |
          git config --global user.name "galadriel1402"
          git config --global user.email "galadriel1402@gmail.com"

      - name: Compile Kernel
        # --- FIX: 'run:' was incorrectly indented ---
        run: |
          chmod +x scripts/compile.sh
          bash scripts/compile.sh

      - name: Zipup outputs
        run: |
          chmod +x scripts/ak3zip.sh
          bash scripts/ak3zip.sh

      - name: Publish release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ZIPNAME }}
          name: "v1.0 Silmaril"
          tag_name: build-${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
